title: Cálculo diferencial e integral
description: Aqui estão disponibilizados uma série de documentos para o estudo de cálculo.
author: Thiago de Paula Oliveira
logo: /calculus/static/img/avatar.png
github: https://github.com/Prof-ThiagoOliveira
about: Agronomy Engineer with PhD in Statistics and Agricultural Experimentation


baseurl: "https://prof-thiagooliveira.github.io/calculus"
url: "https://prof-thiagooliveira.github.io/calculus"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
